### PR TITLE
Generate Linux kernel wrappers dynamically

### PR DESCRIPTION
**Pull request by jpsamaroo**
This should be helpful when writing various kinds of probes, so that we can introspect (and potentially modify) kernel data structures.

### CODE REVIEW

**Comment by jpsamaroo** [comment]
This is blocked on sending some Clang improvements upstream, but I figured I'd post this now.

**Comment by krrutkow** [comment]
@jpsamaroo Have you looked at using [CBinding.jl](https://github.com/analytech-solutions/CBinding.jl)/[CBindingGen.jl](https://github.com/analytech-solutions/CBindingGen.jl) instead?  It already has support for C bitfields, unions, field alignment, etc. and I have used it to wrap Linux headers on projects.

**Comment by jpsamaroo** [comment]
Looks interesting! Here are some initial comments from testing:
- CBindingGen only supports Clang up to 9.x, whereas Julia 1.6 is on 11.x (which is the minimum version of Julia that BPFnative supports). This was easy to workaround via copy-pasta.
- Using multiple libclangs (Julia's internal one, and Clang_jll's) on Linux musl systems such as Alpine Linux doesn't work due to symbol versioning issues in the musl linker, so I patched CBindingGen to use Julia's internal libclang instead.
- After the above, using a simple binding generator I get the following: `ERROR: LoadError: Unable to convert type CBindingGen.LibClang.CXTypeKind(<CXType_FunctionNoProto>(0x0000006e)), not yet implemented`. I imagine I'll need to modify the cursor callback to explicitly skip such cursor types?

**Comment by krrutkow** [comment]
Very interesting!  You are definitely taking the package off-roading a bit!  I am not able to reproduce the problem on my Arch Linux x86_64 setup when parsing the libbpf headers (it works fine), so could you share where in the header the `CXType_FunctionNoProto` type of expression occurs or how I could reproduce your setup?  Also, yes, you should be able to filter out that particular cursor and possibly dependent cursors as well.

**Comment by jpsamaroo** [comment]
If you test with the output of the `bpftool` command in this PR, you'll get a full dump of the kernel's data structures (it's ~2.5M of C definitions on my system). I'll try to find a simple reproducer when I get the chance!

**Comment by krrutkow** [comment]
Wow, that generated code has several challenging issues:

- obsolete, empty-parentheses function declarations (`void func()` instead of `void func(void)`)
- unnamed bitfields
- bitfields with enumeration types

Support for all 3 is nearly complete.  They will probably be available in the next day or so unless more suicidal C is encountered.

**Pull request merged**
